install:
- "./gradlew assembleDebug --stacktrace"
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_EMULATOR_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=20
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".*intel.+"
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
before_install:
- openssl aes-256-cbc -K $encrypted_bcbb3c5eada5_key -iv $encrypted_bcbb3c5eada5_iv
  -in google-services.json.enc -out .\\app\\google-services.json -d
- chmod +x gradlew
- yes | sdkmanager "platforms;android-27" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
script:
- "./gradlew build jacocoTestReport assembleAndroidTest"
- echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL
  --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -skin 768x1280 -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- travis_wait 30 ./gradlew connectedCheck --stacktrace
branches:
  only:
  - master
sudo: true
after_success:
- bash <(curl -s https://codecov.io/bash)
